"""create reservation history

Revision ID: 987b3fe89318
Revises: 7f2ef82b18ba
Create Date: 2026-06-16 00:31:55.954188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987b3fe89318'
down_revision: Union[str, Sequence[str], None] = '7f2ef82b18ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reservation_period'), table_name='reservations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reservation_period'), 'reservations', ['equipment_id', 'start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###
